name: Deployment

on:
  push:
    branches:
      - master
env:
  ENVIRONMENT: ${{secrets.ENVIRONMENT}} | sed 's/./& /g'
  
jobs:
  DeployDEV:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
        run: echo ${{env.ENVIRONMENT}}
        
  DeployPROD:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: echo ${{env.ENVIRONMENT}}
