name: Deployment

on:
  push:
    branches:
      - master
env:
  ENVIRONMENT: ${{secrets.ENVIRONMENT}}
  
jobs:
  DeployDEV:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
        run: echo "${{env}}"
        
  DeployPROD:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: echo "${{env.ENVIRONMENT}}"
