name: Releases

on:
  workflow_dispatch:
  
env:
  ENVIRONMENT: ${{secrets.ENVIRONMENT}}
  
jobs:
  DeployDEV:
    name: DEV environment
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: echo environment variables
        run: echo ${{env.ENVIRONMENT}}
      - name: 'Create env file'
        run: |
          touch .env
          echo ENVIRONMENT=${{env.ENVIRONMENT}} >> .env
          cat .env
        
  DeployPROD:
    name: PROD environment
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: echo environment variables
        run: echo ${{env.ENVIRONMENT}}
