name: Releases

on:
  workflow_dispatch:
  
env:
  ENVIRONMENT: ${{secrets.ENVIRONMENT}} -- | sed 's/./& /g'
  
jobs:
  DeployDEV:
    name: deploy to DEV environment
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: echo environment variables
        run: echo ${{env.ENVIRONMENT}}
        
  DeployPROD:
    name: deploy to PROD environment
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: echo environment variables
        run: echo ${{env.ENVIRONMENT}}
