name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy
        # ...deployment-specific steps
        run: echo "${{secrets.ENVIRONMENT}}"
