name: Deployment

on:
  push:
    branches:
      - master
env:
  ENVIRONMENT: ${{secrets.ENVIRONMENT}}
  
jobs:
  DeployDEV:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Set up secret file
      env:
        ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      run: |
        echo $ENVIRONMENT >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
        
  DeployPROD:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: echo "${{env.ENVIRONMENT}}"
